/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package segta.formularios;

import java.awt.Component;
import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;
import java.awt.event.WindowEvent;
import java.math.BigInteger;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.persistence.EntityManager;
import javax.persistence.EntityManagerFactory;
import javax.persistence.Persistence;
import javax.persistence.Query;
import javax.swing.JOptionPane;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableCellRenderer;
import segta.clases.Localidad;
import segta.clases.Proveedor;
import segta.clases.Provincia;
import segta.controladores.ProveedorJpaController;

/**
 *
 * @author MODERNIZACION3
 */
public class jDialogProveedor extends javax.swing.JDialog {

    /**
     * Creates new form jDialogDescargas
     */
    EntityManagerFactory emf = Persistence.createEntityManagerFactory("SegTAPU");
    EntityManager em = emf.createEntityManager();
    ProveedorJpaController controlador = new ProveedorJpaController(emf);
    String tipo; //identifica si hay que agregar o editar
    Proveedor prov; //objeto seleccionado de la tabla
    Provincia provin;
    Localidad loc;

    public jDialogProveedor(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.jComboLocalidad.enable(false);
        desactivaCampos();
        DefaultTableCellRenderer tcr = new DefaultTableCellRenderer();
        tcr.setHorizontalAlignment(SwingConstants.CENTER);
        jTableProveedores.getColumnModel().getColumn(1).setCellRenderer(tcr);
        jTableProveedores.getColumnModel().getColumn(2).setCellRenderer(tcr);
    }

    public void seleccionarProveedor() {
        /*
        TableModel modelo = (TableModel) jTableProveedores.getModel();

        Descargas d = (Descargas) jTableProveedores.getValueAt(jTableProveedores.getSelectedRow(), 0);

        idDescarga = d.getIdDescargas();

        System.out.print(idDescarga);
         */
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        SegTAPUEntityManager = java.beans.Beans.isDesignTime() ? null : javax.persistence.Persistence.createEntityManagerFactory("SegTAPU").createEntityManager();
        proveedorQuery = java.beans.Beans.isDesignTime() ? null : SegTAPUEntityManager.createQuery("SELECT p FROM Proveedor p WHERE p.baja = 0 ORDER BY p.razonSocial");
        proveedorList = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : org.jdesktop.observablecollections.ObservableCollections.observableList(proveedorQuery.getResultList());
        provinciaQuery = java.beans.Beans.isDesignTime() ? null : SegTAPUEntityManager.createQuery("SELECT p FROM Provincia p");
        provinciaQuery1 = java.beans.Beans.isDesignTime() ? null : SegTAPUEntityManager.createQuery("SELECT p FROM Provincia p");
        provinciaList = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : provinciaQuery1.getResultList();
        localidadQuery = java.beans.Beans.isDesignTime() ? null : SegTAPUEntityManager.createQuery("SELECT l FROM Localidad l ");
        localidadList = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : localidadQuery.getResultList();
        jPanel1 = new javax.swing.JPanel();
        jPanelDatos = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jTextCUIT = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextRazonSocial = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextTelefono = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTextMail = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jTextDireccion = new javax.swing.JTextField();
        jBAceptar = new javax.swing.JButton();
        jBCancelar = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jComboProvincia = new javax.swing.JComboBox<>();
        jComboLocalidad = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jTextRenapa = new javax.swing.JTextField();
        jCBAcopiador = new javax.swing.JCheckBox();
        jPanelTabla = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableProveedores = new javax.swing.JTable();
        jBAgregar = new javax.swing.JButton();
        jBEditar = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jTextRazonBusq = new javax.swing.JTextField();
        jBBuscar = new javax.swing.JButton();
        jBBorrar = new javax.swing.JButton();
        jBVolver1 = new javax.swing.JButton();
        jDialogDescargasFondo = new javax.swing.JLabel();

        Localidad p = new Localidad();
        p.setNombre("Seleccione Localidad");
        localidadList.add(0,p);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("APICULTORES");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jPanelDatos.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "DATOS DEL APICULTOR", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 12))); // NOI18N

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("CUIT");

        jTextCUIT.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, jTableProveedores, org.jdesktop.beansbinding.ELProperty.create("${selectedElement.cuit}"), jTextCUIT, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("RAZÓN SOCIAL");

        jTextRazonSocial.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("DIRECCION");

        jTextTelefono.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, jTableProveedores, org.jdesktop.beansbinding.ELProperty.create("${selectedElement.telefono}"), jTextTelefono, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("MAIL");

        jTextMail.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, jTableProveedores, org.jdesktop.beansbinding.ELProperty.create("${selectedElement.mail}"), jTextMail, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        jTextMail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextMailActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("TELEFONO");

        jTextDireccion.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, jTableProveedores, org.jdesktop.beansbinding.ELProperty.create("${selectedElement.direccion}"), jTextDireccion, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        jBAceptar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jBAceptar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/segta/imagenes/aceptar.png"))); // NOI18N
        jBAceptar.setText("ACEPTAR");
        jBAceptar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jBAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAceptarActionPerformed(evt);
            }
        });

        jBCancelar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jBCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/segta/imagenes/cancerlar.png"))); // NOI18N
        jBCancelar.setText("CANCELAR");
        jBCancelar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jBCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBCancelarActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("LOCALIDAD");

        jComboProvincia.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        org.jdesktop.swingbinding.JComboBoxBinding jComboBoxBinding = org.jdesktop.swingbinding.SwingBindings.createJComboBoxBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, provinciaList, jComboProvincia);
        bindingGroup.addBinding(jComboBoxBinding);

        jComboProvincia.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboProvinciaItemStateChanged(evt);
            }
        });
        jComboProvincia.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jComboProvinciaFocusGained(evt);
            }
        });
        jComboProvincia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboProvinciaActionPerformed(evt);
            }
        });

        jComboLocalidad.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jComboBoxBinding = org.jdesktop.swingbinding.SwingBindings.createJComboBoxBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, localidadList, jComboLocalidad);
        bindingGroup.addBinding(jComboBoxBinding);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setText("PROVINCIA");

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setText("RENAPA");

        jTextRenapa.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, jTableProveedores, org.jdesktop.beansbinding.ELProperty.create("${selectedElement.renapa}"), jTextRenapa, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        jCBAcopiador.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jCBAcopiador.setText("ACOPIADOR");

        javax.swing.GroupLayout jPanelDatosLayout = new javax.swing.GroupLayout(jPanelDatos);
        jPanelDatos.setLayout(jPanelDatosLayout);
        jPanelDatosLayout.setHorizontalGroup(
            jPanelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDatosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelDatosLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jBAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jBCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelDatosLayout.createSequentialGroup()
                        .addGroup(jPanelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelDatosLayout.createSequentialGroup()
                                .addGroup(jPanelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jComboProvincia, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jTextCUIT, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextRenapa)
                                    .addComponent(jTextRazonSocial))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel6)
                                        .addComponent(jLabel8)
                                        .addComponent(jLabel7))
                                    .addComponent(jLabel9))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jComboLocalidad, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jTextMail, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jTextTelefono, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jTextDireccion, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addGap(4, 4, 4))
                            .addGroup(jPanelDatosLayout.createSequentialGroup()
                                .addComponent(jCBAcopiador, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        jPanelDatosLayout.setVerticalGroup(
            jPanelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDatosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelDatosLayout.createSequentialGroup()
                        .addGroup(jPanelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jTextRazonSocial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jTextCUIT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8)
                            .addComponent(jTextTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel6)
                        .addComponent(jTextDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel7)
                        .addComponent(jTextMail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel11)
                        .addComponent(jTextRenapa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboProvincia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(jLabel9)
                    .addComponent(jComboLocalidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jCBAcopiador)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addGroup(jPanelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        jPanelTabla.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "APICULTOR", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 12))); // NOI18N

        jTableProveedores.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTableProveedores.getTableHeader().setFont(new java.awt.Font("Tahoma", 0, 14));

        org.jdesktop.swingbinding.JTableBinding jTableBinding = org.jdesktop.swingbinding.SwingBindings.createJTableBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, proveedorList, jTableProveedores);
        org.jdesktop.swingbinding.JTableBinding.ColumnBinding columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${idProveedor}"));
        columnBinding.setColumnName("Id Proveedor");
        columnBinding.setColumnClass(Integer.class);
        columnBinding.setEditable(false);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${razonSocial}"));
        columnBinding.setColumnName("Razon Social");
        columnBinding.setColumnClass(String.class);
        columnBinding.setEditable(false);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${cuit}"));
        columnBinding.setColumnName("Cuit");
        columnBinding.setColumnClass(java.math.BigInteger.class);
        columnBinding.setEditable(false);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${telefono}"));
        columnBinding.setColumnName("Telefono");
        columnBinding.setColumnClass(java.math.BigInteger.class);
        columnBinding.setEditable(false);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${mail}"));
        columnBinding.setColumnName("Mail");
        columnBinding.setColumnClass(String.class);
        columnBinding.setEditable(false);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${direccion}"));
        columnBinding.setColumnName("Direccion");
        columnBinding.setColumnClass(String.class);
        columnBinding.setEditable(false);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${acopiador}"));
        columnBinding.setColumnName("Acopiador");
        columnBinding.setColumnClass(Boolean.class);
        columnBinding.setEditable(false);
        bindingGroup.addBinding(jTableBinding);
        jTableBinding.bind();
        jTableProveedores.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableProveedoresMouseClicked(evt);
            }
        });
        jTableProveedores.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTableProveedoresKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTableProveedoresKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(jTableProveedores);
        if (jTableProveedores.getColumnModel().getColumnCount() > 0) {
            jTableProveedores.getColumnModel().getColumn(6).setMinWidth(70);
            jTableProveedores.getColumnModel().getColumn(6).setPreferredWidth(70);
            jTableProveedores.getColumnModel().getColumn(6).setMaxWidth(70);
        }

        jBAgregar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jBAgregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/segta/imagenes/add icono.png"))); // NOI18N
        jBAgregar.setText("AGREGAR");
        jBAgregar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jBAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAgregarActionPerformed(evt);
            }
        });

        jBEditar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jBEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/segta/imagenes/editar.png"))); // NOI18N
        jBEditar.setText("EDITAR");
        jBEditar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jBEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBEditarActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setText("RAZÓN SOCIAL");

        jTextRazonBusq.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jBBuscar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jBBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/segta/imagenes/buscar icono.png"))); // NOI18N
        jBBuscar.setText("BUSCAR");
        jBBuscar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jBBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBBuscarActionPerformed(evt);
            }
        });

        jBBorrar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jBBorrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/segta/imagenes/borrar.png"))); // NOI18N
        jBBorrar.setText("BORRAR");
        jBBorrar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jBBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBBorrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelTablaLayout = new javax.swing.GroupLayout(jPanelTabla);
        jPanelTabla.setLayout(jPanelTablaLayout);
        jPanelTablaLayout.setHorizontalGroup(
            jPanelTablaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTablaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelTablaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanelTablaLayout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addContainerGap())
                    .addGroup(jPanelTablaLayout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextRazonBusq, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                        .addComponent(jBAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBBorrar, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        jPanelTablaLayout.setVerticalGroup(
            jPanelTablaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTablaLayout.createSequentialGroup()
                .addGroup(jPanelTablaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jBBorrar, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanelTablaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jBEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jBAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jBBuscar)
                        .addComponent(jTextRazonBusq, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel12)))
                .addGap(18, 19, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 193, Short.MAX_VALUE)
                .addContainerGap())
        );

        jBVolver1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/segta/imagenes/volver icono.png"))); // NOI18N
        jBVolver1.setText("VOLVER");
        jBVolver1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBVolver1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelTabla, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanelDatos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jBVolver1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelDatos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelTabla, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBVolver1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 80, 1020, 600));

        jDialogDescargasFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/segta/imagenes/fondo dialog.png"))); // NOI18N
        getContentPane().add(jDialogDescargasFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -20, -1, 810));

        bindingGroup.bind();

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBAgregarActionPerformed

        tipo = "nuevo";
        desactivaTabla();
        limpiaCampos();
        activaCampos();
        this.jComboProvincia.addItemListener(new ItemListener() {

            @Override
            public void itemStateChanged(ItemEvent e) {
                if (e.getStateChange() == ItemEvent.SELECTED) {
                    // los nuevos registros son agregados al MODEL del JCombo HIJO
                    Object item = e.getItem();
                    Query ql;
                    ql = SegTAPUEntityManager.createQuery("SELECT l FROM Localidad l WHERE l.idProvincia = :pro ");
                    ql.setParameter("pro", item);
                    localidadQuery = java.beans.Beans.isDesignTime() ? null : ql;
                    localidadList.clear();
                    localidadList.addAll(localidadQuery.getResultList());
                }
            }
        });
        this.jTextRazonSocial.requestFocus();
    }//GEN-LAST:event_jBAgregarActionPerformed


    private void jBEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBEditarActionPerformed

        if (this.jTableProveedores.getSelectedRowCount() == 1) {

            seleccionaProveedor();
            desactivaTabla();
            activaCampos();
            tipo = "edit";

        } else {
            JOptionPane.showMessageDialog(null, "Debe seleccionar un apicultor", "Validación", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_jBEditarActionPerformed

    private void jTextMailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextMailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextMailActionPerformed

    private void jBAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBAceptarActionPerformed
        int flagValidacion = 0;
        String razSoc = this.jTextRazonSocial.getText();
        BigInteger cuit = null;
        BigInteger tel = null;

        //Razon social no null
        if (razSoc.isEmpty()) {
            flagValidacion = 1;
            JOptionPane.showMessageDialog(null, "Ingrese una Razón Social", "Validación", JOptionPane.WARNING_MESSAGE);
            this.jTextRazonSocial.requestFocus();
        }
        //cuit numerico
        if (!this.jTextCUIT.getText().isEmpty()) {

            try {
                cuit = new BigInteger(this.jTextCUIT.getText());

            } catch (Exception ex) {
                flagValidacion = 1;
                JOptionPane.showMessageDialog(null, "Ingrese sólo números", "Información", JOptionPane.WARNING_MESSAGE);
                this.jTextCUIT.requestFocus();

            }
        }

        //telefono numerico
        if (!this.jTextTelefono.getText().isEmpty()) {

            try {
                tel = new BigInteger(this.jTextTelefono.getText());

            } catch (Exception ex) {
                flagValidacion = 1;
                JOptionPane.showMessageDialog(null, "Ingrese sólo números", "Información", JOptionPane.WARNING_MESSAGE);
                this.jTextTelefono.requestFocus();

            }
        }
        // Localliad seleccionada
        loc = localidadList.get(this.jComboLocalidad.getSelectedIndex());
        if (loc.getIdLocalidad() == null) {
            flagValidacion = 1;
            JOptionPane.showMessageDialog(null, "Seleccione Localidad", "Información", JOptionPane.WARNING_MESSAGE);
            jComboLocalidad.requestFocus();
        }

        if (flagValidacion == 0) {

            if (tipo.equals("nuevo")) {
                Proveedor nuevoProv = new Proveedor();
                nuevoProv.setRazonSocial(razSoc);
                nuevoProv.setCuit(cuit);
                nuevoProv.setDireccion(this.jTextDireccion.getText());
                nuevoProv.setTelefono(tel);
                nuevoProv.setMail(this.jTextMail.getText());
                nuevoProv.setIdLocalidad(loc);
                nuevoProv.setRenapa(this.jTextRenapa.getText());
                nuevoProv.setBaja(0);
                if (jCBAcopiador.isSelected()) {
                    nuevoProv.setAcopiador(true);
                }

                try {

                    controlador.create(nuevoProv);
                    JOptionPane.showMessageDialog(null, "Apicultor creado con éxito", "Información", JOptionPane.INFORMATION_MESSAGE);
                    limpiaCampos();

                } catch (Exception ex) {
                    Logger.getLogger(jDialogProveedor.class.getName()).log(Level.SEVERE, null, ex);
                    JOptionPane.showMessageDialog(null, "Error al crear el apicultor", "Información", JOptionPane.ERROR_MESSAGE);
                }

            } else {
                prov.setRazonSocial(razSoc);
                prov.setCuit(cuit);
                prov.setDireccion(this.jTextDireccion.getText());
                prov.setTelefono(tel);
                prov.setMail(this.jTextMail.getText());
                prov.setIdLocalidad(loc);
                prov.setRenapa(this.jTextRenapa.getText());
                if (jCBAcopiador.isSelected()) {
                    prov.setAcopiador(true);
                } else {
                    prov.setAcopiador(false);
                }
                try {

                    controlador.edit(prov);
                    JOptionPane.showMessageDialog(null, "Apicultor editado con éxito", "Información", JOptionPane.INFORMATION_MESSAGE);
                    limpiaCampos();

                } catch (Exception ex) {
                    Logger.getLogger(jDialogProveedor.class.getName()).log(Level.SEVERE, null, ex);
                    JOptionPane.showMessageDialog(null, "Error al editar el apicultor", "Información", JOptionPane.ERROR_MESSAGE);
                }

            }
            limpiaCampos();
            desactivaCampos();
            activaTabla();
            actualizaTabla();

        }

    }//GEN-LAST:event_jBAceptarActionPerformed
    //boton cancelar
    private void jBCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBCancelarActionPerformed
        // TODO add your handling code here:
        limpiaCampos();
        desactivaCampos();
        activaTabla();

    }//GEN-LAST:event_jBCancelarActionPerformed

    private void jTableProveedoresMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableProveedoresMouseClicked
        // TODO add your handling code here:
        seleccionaProveedor();
    }//GEN-LAST:event_jTableProveedoresMouseClicked

    private void jTableProveedoresKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTableProveedoresKeyReleased
        seleccionaProveedor();
    }//GEN-LAST:event_jTableProveedoresKeyReleased

    private void jTableProveedoresKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTableProveedoresKeyPressed
        seleccionaProveedor();
    }//GEN-LAST:event_jTableProveedoresKeyPressed

    private void jComboProvinciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboProvinciaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboProvinciaActionPerformed

    private void jComboProvinciaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jComboProvinciaFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboProvinciaFocusGained

    private void jComboProvinciaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboProvinciaItemStateChanged

//        actualizarLocalidades();   
    }//GEN-LAST:event_jComboProvinciaItemStateChanged

    private void jBVolver1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBVolver1ActionPerformed
        this.processWindowEvent(new WindowEvent(this, WindowEvent.WINDOW_CLOSING));
    }//GEN-LAST:event_jBVolver1ActionPerformed

    private void jBBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBBuscarActionPerformed
        Query ql;
        String queryTxt = "SELECT p FROM Proveedor p WHERE 1=1 AND p.baja = 0";
        if (this.jTextRazonBusq.getText() != null) {
            String nom = this.jTextRazonBusq.getText();
            queryTxt = queryTxt + " AND p.razonSocial like '%" + nom + "%' ";

        }
        ql = em.createQuery(queryTxt);
        proveedorQuery = java.beans.Beans.isDesignTime() ? null : ql;
        proveedorList.clear();
        proveedorList.addAll(proveedorQuery.getResultList());
    }//GEN-LAST:event_jBBuscarActionPerformed

    private void jBBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBBorrarActionPerformed
        if (this.jTableProveedores.getSelectedRowCount() == 1) {

            seleccionaProveedor();
            desactivaTabla();
            //activaCampos();
            if (JOptionPane.showConfirmDialog(null, "Desea eliminar el Apicultor?", "WARNING", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
                prov.setBaja(1);
                try {
                    controlador.edit(prov);
                } catch (Exception ex) {
                    Logger.getLogger(jDialogProveedor.class.getName()).log(Level.SEVERE, null, ex);
                }
            } //else { // no option } ;
        } else {
            JOptionPane.showMessageDialog(null, "Debe seleccionar un apicultor", "Validación", JOptionPane.WARNING_MESSAGE);
        }
        actualizaTabla();
        limpiaCampos();
        activaTabla();
    }//GEN-LAST:event_jBBorrarActionPerformed
    //Convierte la fila seleccionada en objeto proveedor
    @SuppressWarnings("empty-statement")
    private void seleccionaProveedor() {

        jCBAcopiador.setSelected(false);
        if (this.jTableProveedores.getSelectedRowCount() == 1) {
            prov = proveedorList.get(jTableProveedores.getSelectedRow());
            this.jTextRazonSocial.setText(prov.getRazonSocial());
//            this.jTextRenapa.setText(prov.getRenapa()); 
            if (prov.getAcopiador() != null) {
                if (prov.getAcopiador().equals(true)) {
                    this.jCBAcopiador.setSelected(true);
                } else {
                    this.jCBAcopiador.setSelected(false);
                }
            } else {
                this.jCBAcopiador.setSelected(false);
            }

//            this.jTextCUIT.setText(prov.getCuit().toString());
//            this.jTextDireccion.setText(prov.getDireccion());
//            this.jTextMail.setText(prov.getMail()); 
//            this.jTextTelefono.setText(prov.getTelefono().toString());
//            this.jComboProvincia.setSelectedItem(prov.getIdLocalidad().getIdProvincia());
//            this.jComboLocalidad.setSelectedItem(prov.getIdLocalidad());
//            try{
//                this.jTextCUIT.setText(prov.getCuit().toString()); 
//            } catch (Exception ex){
//                this.jTextCUIT.setText("");
//            };
//            try{
//                this.jTextDireccion.setText(prov.getDireccion()); 
//            } catch (Exception ex){
//                this.jTextDireccion.setText("");
//            };
//            try{
//                this.jTextMail.setText(prov.getMail()); 
//            } catch (Exception ex){
//                this.jTextMail.setText("");
//            };
//            try{
//                this.jTextTelefono.setText(prov.getTelefono().toString()); 
//            } catch (Exception ex){
//                this.jTextTelefono.setText("");
//            };
            try {
                this.jComboProvincia.setSelectedItem(prov.getIdLocalidad().getIdProvincia());

            } catch (Exception ex) {

            };
            try {
                this.jComboLocalidad.setSelectedItem(prov.getIdLocalidad());
            } catch (Exception ex) {

            };
        }
    }

    //Limpia los textFields
    private void limpiaCampos() {
        this.jTextRazonSocial.setText("");
        this.jTextCUIT.setText("");
        this.jTextDireccion.setText("");
        this.jTextMail.setText("");
        this.jTextTelefono.setText("");
        this.jTextRenapa.setText("");
        this.jCBAcopiador.setSelected(false);
    }

    //desactiva los textfields y botones de aceptar y cancelar
    private void desactivaCampos() {
        for (Component component : jPanelDatos.getComponents()) {
            component.setEnabled(false);
        }

    }

    //activa los textfields y botones de aceptar y cancelar
    private void activaCampos() {
        for (Component component : jPanelDatos.getComponents()) {
            component.setEnabled(true);
        }

    }

    //desactiva botones de agregar y editar y tabla 
    private void desactivaTabla() {
        for (Component component : jPanelTabla.getComponents()) {
            component.setEnabled(false);
        }
        this.jTableProveedores.setEnabled(false);

    }
    //activa botones de agregar y editar y tabla 

    private void activaTabla() {
        for (Component component : jPanelTabla.getComponents()) {
            component.setEnabled(true);
        }
        this.jTableProveedores.setEnabled(true);

    }

    private void actualizaTabla() {
        proveedorList.clear();
        proveedorList.addAll(proveedorQuery.getResultList());
    }

//    public void actualizarLocalidades(){
//         
//        try{
//            
//            provin= provinciaList.get(this.jComboProvincia.getSelectedIndex());  
//            Query ql;
//            ql = SegTAPUEntityManager.createQuery("SELECT l FROM Localidad l WHERE l.idProvincia = :pro");
//            ql.setParameter("pro", provin);
//            localidadQuery = java.beans.Beans.isDesignTime() ? null : ql;
//            this.SegTAPUEntityManager.clear();
//            localidadList.clear();
//            localidadList.addAll(localidadQuery.getResultList());  
//            System.out.println(provin);
//            
//        
//        }catch (Exception ex){
//            this.jTextCUIT.setText("aaaa");
//        }
//    }
//    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jDialogProveedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jDialogProveedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jDialogProveedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jDialogProveedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                jDialogProveedor dialog = new jDialogProveedor(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.persistence.EntityManager SegTAPUEntityManager;
    private javax.swing.JButton jBAceptar;
    private javax.swing.JButton jBAgregar;
    private javax.swing.JButton jBBorrar;
    private javax.swing.JButton jBBuscar;
    private javax.swing.JButton jBCancelar;
    private javax.swing.JButton jBEditar;
    private javax.swing.JButton jBVolver1;
    private javax.swing.JCheckBox jCBAcopiador;
    private javax.swing.JComboBox<String> jComboLocalidad;
    private javax.swing.JComboBox<String> jComboProvincia;
    private javax.swing.JLabel jDialogDescargasFondo;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelDatos;
    private javax.swing.JPanel jPanelTabla;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableProveedores;
    private javax.swing.JTextField jTextCUIT;
    private javax.swing.JTextField jTextDireccion;
    private javax.swing.JTextField jTextMail;
    private javax.swing.JTextField jTextRazonBusq;
    private javax.swing.JTextField jTextRazonSocial;
    private javax.swing.JTextField jTextRenapa;
    private javax.swing.JTextField jTextTelefono;
    private java.util.List<segta.clases.Localidad> localidadList;
    private javax.persistence.Query localidadQuery;
    private java.util.List<segta.clases.Proveedor> proveedorList;
    private javax.persistence.Query proveedorQuery;
    private java.util.List<segta.clases.Provincia> provinciaList;
    private javax.persistence.Query provinciaQuery;
    private javax.persistence.Query provinciaQuery1;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
}
