/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package segta.formularios;

import java.awt.Component;
import java.awt.event.WindowEvent;
import static java.lang.Float.parseFloat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.HashMap;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.persistence.EntityManager;
import javax.persistence.EntityManagerFactory;
import javax.persistence.Persistence;
import javax.swing.DefaultListCellRenderer;
import javax.swing.JList;
import javax.swing.JOptionPane;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableCellRenderer;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.view.JasperViewer;
import segta.Conexion;
import segta.clases.Analisis;
import segta.clases.Analisisdeterminacion;
import segta.clases.Descargas;
import segta.clases.Determinacion;
import segta.clases.Lote;
import segta.controladores.AnalisisJpaController;
import segta.controladores.AnalisisdeterminacionJpaController;
import segta.controladores.ContratoJpaController;
import segta.controladores.exceptions.NonexistentEntityException;

/**
 *
 * @author MODERNIZACION3
 */
public class jDialogAnalisis extends javax.swing.JDialog {

    /**
     * Creates new form jDialogDescargas
     */
    EntityManagerFactory emf = Persistence.createEntityManagerFactory("SegTAPU");
    EntityManager em = emf.createEntityManager();
    AnalisisJpaController controlador = new AnalisisJpaController(emf);
    ContratoJpaController controladorT = new ContratoJpaController(emf);
    AnalisisdeterminacionJpaController controladorDet = new AnalisisdeterminacionJpaController(emf);
    String tipo; //identifica si hay que agregar o editar
    Analisis anali; //objeto seleccionado de la tabla
    Analisisdeterminacion AD;
    Lote lote;

    public jDialogAnalisis(javax.swing.JDialog parent, boolean modal, Lote lo) {
        super(parent, modal);
        lote = lo;
        initComponents();

        jCBDeterminacion.setRenderer(new DefaultListCellRenderer() {
            @Override
            public Component getListCellRendererComponent(JList<?> list, Object value, int index, boolean isSelected, boolean cellHasFocus) {
                if (value instanceof Determinacion) {
                    Determinacion det = (Determinacion) value;
                    return super.getListCellRendererComponent(list, det.getNombre() + " (" + det.getUnidad() + ")", index, isSelected, cellHasFocus); //To change body of generated methods, choose Tools | Templates.

                }
                return super.getListCellRendererComponent(list, value, index, isSelected, cellHasFocus); //To change body of generated methods, choose Tools | Templates.
            }
        });
        actualizaTablaDeterminacion();
        desactivaCampos();
        DefaultTableCellRenderer tcr = new DefaultTableCellRenderer();
        tcr.setHorizontalAlignment(SwingConstants.CENTER);
        jTableAnalisis.getColumnModel().getColumn(0).setCellRenderer(tcr);
        jTableAnalisis.getColumnModel().getColumn(2).setCellRenderer(tcr);
        this.jTextLote.setText(lo.getLote());
        this.jTextDescripcion.setText(lo.getDescripcion());
        this.jTextCliente.setText(lo.getIdLoteContrato().getIdContrato().getIdCliente().getRazonSocial());
        this.jLDeterminaciones.setText(lote.getIdLoteContrato().getIdContrato().getDeterminaciones());
        this.jLDeterminaciones.setEnabled(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        SegTAPUEntityManager = java.beans.Beans.isDesignTime() ? null : javax.persistence.Persistence.createEntityManagerFactory("SegTAPU").createEntityManager();
        analisisQuery = java.beans.Beans.isDesignTime() ? null : SegTAPUEntityManager.createQuery("SELECT a FROM Analisis a WHERE a.idLote=:pLote").setParameter("pLote", lote);
        analisisList = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : org.jdesktop.observablecollections.ObservableCollections.observableList(analisisQuery.getResultList()) ;
        determinacionQuery = java.beans.Beans.isDesignTime() ? null : SegTAPUEntityManager.createQuery("SELECT d FROM Determinacion d");
        determinacionList = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : determinacionQuery.getResultList();
        analisisdeterminacionQuery = java.beans.Beans.isDesignTime() ? null : SegTAPUEntityManager.createQuery("SELECT a FROM Analisisdeterminacion a");
        analisisdeterminacionList = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : org.jdesktop.observablecollections.ObservableCollections.observableList(analisisdeterminacionQuery.getResultList());
        jPanel1 = new javax.swing.JPanel();
        jBVolver = new javax.swing.JButton();
        jPanelDatos = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jBAceptar = new javax.swing.JButton();
        jBCancelar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextObs = new javax.swing.JTextArea();
        dCFecha = new datechooser.beans.DateChooserCombo();
        jPanelTabla = new javax.swing.JPanel();
        jBAgregar = new javax.swing.JButton();
        jBEditar = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTableAnalisis = new javax.swing.JTable();
        jCBDeterminacion = new javax.swing.JComboBox<>();
        jTValorDet = new javax.swing.JTextField();
        jBAgregar1 = new javax.swing.JButton();
        jBEditar1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableDeterminacion = new javax.swing.JTable();
        jBImprimir = new javax.swing.JButton();
        jPanelDatos1 = new javax.swing.JPanel();
        jTextLote = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jTextDescripcion = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jTextCliente = new javax.swing.JTextField();
        jLDeterminaciones = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jDialogDescargasFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("ANALISIS");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jBVolver.setIcon(new javax.swing.ImageIcon(getClass().getResource("/segta/imagenes/volver icono.png"))); // NOI18N
        jBVolver.setText("VOLVER");
        jBVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBVolverActionPerformed(evt);
            }
        });

        jPanelDatos.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "DATOS DEL ANALISIS", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 12))); // NOI18N

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("OBSERVACIONES");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("FECHA");

        jBAceptar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jBAceptar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/segta/imagenes/aceptar.png"))); // NOI18N
        jBAceptar.setText("ACEPTAR");
        jBAceptar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jBAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAceptarActionPerformed(evt);
            }
        });

        jBCancelar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jBCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/segta/imagenes/cancerlar.png"))); // NOI18N
        jBCancelar.setText("CANCELAR");
        jBCancelar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jBCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBCancelarActionPerformed(evt);
            }
        });

        jTextObs.setColumns(20);
        jTextObs.setRows(5);
        jTextObs.setEnabled(false);
        jScrollPane2.setViewportView(jTextObs);

        dCFecha.setFormat(2);
        dCFecha.setWeekStyle(datechooser.view.WeekDaysStyle.SHORT);
        dCFecha.setFieldFont(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 14));

        javax.swing.GroupLayout jPanelDatosLayout = new javax.swing.GroupLayout(jPanelDatos);
        jPanelDatos.setLayout(jPanelDatosLayout);
        jPanelDatosLayout.setHorizontalGroup(
            jPanelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDatosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(dCFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelDatosLayout.createSequentialGroup()
                        .addGap(0, 354, Short.MAX_VALUE)
                        .addComponent(jBAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2))
                .addContainerGap())
        );
        jPanelDatosLayout.setVerticalGroup(
            jPanelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDatosLayout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelDatosLayout.createSequentialGroup()
                        .addComponent(jBCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jBAceptar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(jPanelDatosLayout.createSequentialGroup()
                .addGroup(jPanelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanelDatosLayout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(jPanelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(jLabel7)))
                    .addGroup(jPanelDatosLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(dCFecha, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanelTabla.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "ANALISIS", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 12))); // NOI18N

        jBAgregar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jBAgregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/segta/imagenes/add icono.png"))); // NOI18N
        jBAgregar.setText("AGREGAR");
        jBAgregar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jBAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAgregarActionPerformed(evt);
            }
        });

        jBEditar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jBEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/segta/imagenes/editar.png"))); // NOI18N
        jBEditar.setText("EDITAR");
        jBEditar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jBEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBEditarActionPerformed(evt);
            }
        });

        org.jdesktop.swingbinding.JTableBinding jTableBinding = org.jdesktop.swingbinding.SwingBindings.createJTableBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, analisisList, jTableAnalisis);
        org.jdesktop.swingbinding.JTableBinding.ColumnBinding columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${idAnalisis}"));
        columnBinding.setColumnName("Numero");
        columnBinding.setColumnClass(Integer.class);
        columnBinding.setEditable(false);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${fecha}"));
        columnBinding.setColumnName("Fecha");
        columnBinding.setColumnClass(java.util.Date.class);
        columnBinding.setEditable(false);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${observaciones}"));
        columnBinding.setColumnName("Observaciones");
        columnBinding.setColumnClass(String.class);
        columnBinding.setEditable(false);
        bindingGroup.addBinding(jTableBinding);
        jTableBinding.bind();
        jTableAnalisis.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableAnalisisMouseClicked(evt);
            }
        });
        jTableAnalisis.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTableAnalisisKeyReleased(evt);
            }
        });
        jScrollPane3.setViewportView(jTableAnalisis);

        org.jdesktop.swingbinding.JComboBoxBinding jComboBoxBinding = org.jdesktop.swingbinding.SwingBindings.createJComboBoxBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, determinacionList, jCBDeterminacion);
        bindingGroup.addBinding(jComboBoxBinding);

        jTValorDet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTValorDetActionPerformed(evt);
            }
        });

        jBAgregar1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jBAgregar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/segta/imagenes/add icono.png"))); // NOI18N
        jBAgregar1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jBAgregar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAgregar1ActionPerformed(evt);
            }
        });

        jBEditar1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jBEditar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/segta/imagenes/borrar.png"))); // NOI18N
        jBEditar1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jBEditar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBEditar1ActionPerformed(evt);
            }
        });

        jTableBinding = org.jdesktop.swingbinding.SwingBindings.createJTableBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, analisisdeterminacionList, jTableDeterminacion);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${idDeterminacion.nombre}"));
        columnBinding.setColumnName(" Determinacion");
        columnBinding.setColumnClass(String.class);
        columnBinding.setEditable(false);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${valor}"));
        columnBinding.setColumnName("Valor");
        columnBinding.setColumnClass(String.class);
        columnBinding.setEditable(false);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${idDeterminacion.unidad}"));
        columnBinding.setColumnName("Unidad");
        columnBinding.setColumnClass(String.class);
        columnBinding.setEditable(false);
        bindingGroup.addBinding(jTableBinding);
        jTableBinding.bind();
        jScrollPane1.setViewportView(jTableDeterminacion);

        jBImprimir.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jBImprimir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/segta/imagenes/imprimir icono.png"))); // NOI18N
        jBImprimir.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jBImprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBImprimirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelTablaLayout = new javax.swing.GroupLayout(jPanelTabla);
        jPanelTabla.setLayout(jPanelTablaLayout);
        jPanelTablaLayout.setHorizontalGroup(
            jPanelTablaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTablaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelTablaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanelTablaLayout.createSequentialGroup()
                        .addComponent(jBImprimir, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jBAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 348, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanelTablaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelTablaLayout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jCBDeterminacion, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanelTablaLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanelTablaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelTablaLayout.createSequentialGroup()
                                .addComponent(jBAgregar1, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jBEditar1, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jTValorDet))))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );
        jPanelTablaLayout.setVerticalGroup(
            jPanelTablaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTablaLayout.createSequentialGroup()
                .addGroup(jPanelTablaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanelTablaLayout.createSequentialGroup()
                        .addGroup(jPanelTablaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jBEditar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jBAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jBImprimir, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanelTablaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelTablaLayout.createSequentialGroup()
                                .addGap(60, 60, 60)
                                .addComponent(jCBDeterminacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTValorDet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanelTablaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jBAgregar1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jBEditar1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanelTablaLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        jPanelDatos1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "LOTE", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 12))); // NOI18N

        jTextLote.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextLote.setEnabled(false);
        jTextLote.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextLoteActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("DESCRIPCION");

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setText("LOTE");

        jTextDescripcion.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextDescripcion.setEnabled(false);

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setText("CLIENTE");

        jTextCliente.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextCliente.setEnabled(false);

        javax.swing.GroupLayout jPanelDatos1Layout = new javax.swing.GroupLayout(jPanelDatos1);
        jPanelDatos1.setLayout(jPanelDatos1Layout);
        jPanelDatos1Layout.setHorizontalGroup(
            jPanelDatos1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDatos1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextLote, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextDescripcion, javax.swing.GroupLayout.DEFAULT_SIZE, 365, Short.MAX_VALUE))
        );
        jPanelDatos1Layout.setVerticalGroup(
            jPanelDatos1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDatos1Layout.createSequentialGroup()
                .addGap(0, 11, Short.MAX_VALUE)
                .addGroup(jPanelDatos1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelDatos1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel11)
                        .addComponent(jTextCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel9)
                        .addComponent(jTextDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelDatos1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel10)
                        .addComponent(jTextLote, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        jLDeterminaciones.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        jLabel1.setText("DETERMINACIONES DEL CONTRATO");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jPanelDatos1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanelDatos, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLDeterminaciones, javax.swing.GroupLayout.PREFERRED_SIZE, 857, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jBVolver, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jPanelTabla, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(41, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelDatos1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelDatos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(13, 13, 13)
                .addComponent(jPanelTabla, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addGap(1, 1, 1)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jBVolver, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLDeterminaciones, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(139, 139, 139))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 30, 1070, 660));

        jDialogDescargasFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/segta/imagenes/fondo dialog.png"))); // NOI18N
        getContentPane().add(jDialogDescargasFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -20, 1220, 770));

        bindingGroup.bind();

        pack();
    }// </editor-fold>//GEN-END:initComponents


    private void jBAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBAgregarActionPerformed
        tipo = "nuevo";
        desactivaTabla();
        limpiaCampos();
        activaCampos();
        this.dCFecha.requestFocus();


    }//GEN-LAST:event_jBAgregarActionPerformed


    private void jBEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBEditarActionPerformed

        if (this.jTableAnalisis.getSelectedRowCount() == 1) {

            seleccionaAnalisis();
            desactivaTabla();
            activaCampos();
            try {
                Calendar cal = Calendar.getInstance();
                cal.setTime(anali.getFecha());
                this.dCFecha.setSelectedDate(cal);
            } catch (Exception ex) {
                Logger.getLogger(jDialogAnalisis.class.getName()).log(Level.SEVERE, null, ex);
            }

            tipo = "edit";

        } else {
            JOptionPane.showMessageDialog(null, "Debe seleccionar un Analisis", "Validación", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_jBEditarActionPerformed

    private void jBAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBAceptarActionPerformed

        Date fecha = obtieneFecha();
        String obs = this.jTextObs.getText();

        if (tipo.equals("nuevo")) {
            Analisis nuevoAnali = new Analisis();
            nuevoAnali.setIdLote(lote);
            nuevoAnali.setFecha(fecha);
            nuevoAnali.setObservaciones(obs);

            try {

                controlador.create(nuevoAnali);
                JOptionPane.showMessageDialog(null, "Analisis creado con éxito", "Información", JOptionPane.INFORMATION_MESSAGE);

            } catch (Exception ex) {
                Logger.getLogger(jDialogAnalisis.class.getName()).log(Level.SEVERE, null, ex);
                JOptionPane.showMessageDialog(null, "Error al crear el analisis", "Información", JOptionPane.ERROR_MESSAGE);
            }

        } else {
            anali.setObservaciones(obs);
            anali.setFecha(fecha);
            try {

                controlador.edit(anali);
                JOptionPane.showMessageDialog(null, "Analisis editado con éxito", "Información", JOptionPane.INFORMATION_MESSAGE);

            } catch (Exception ex) {
                Logger.getLogger(jDialogAnalisis.class.getName()).log(Level.SEVERE, null, ex);
                JOptionPane.showMessageDialog(null, "Error al editar el analisis", "Información", JOptionPane.ERROR_MESSAGE);
            }

        }

        limpiaCampos();
        desactivaCampos();
        activaTabla();
        actualizaTabla();
        actualizaTablaDeterminacion();


    }//GEN-LAST:event_jBAceptarActionPerformed
    //boton cancelar
    private void jBCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBCancelarActionPerformed
        // TODO add your handling code here:
        limpiaCampos();
        desactivaCampos();
        activaTabla();

    }//GEN-LAST:event_jBCancelarActionPerformed

    private void jTextLoteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextLoteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextLoteActionPerformed

    private void jBAgregar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBAgregar1ActionPerformed
        if (this.jTableAnalisis.getSelectedRowCount() == 1) {
            seleccionaAnalisis();
            int flagValidacion = 0;
            String val = "";

            //Valor numerico
            if (this.jTValorDet.getText().isEmpty()) {
                flagValidacion = 1;
                JOptionPane.showMessageDialog(null, "Debe ingresar un valor de determinacion", "Información", JOptionPane.WARNING_MESSAGE);
                this.jTValorDet.requestFocus();
            }

            if (flagValidacion == 0) {
                try {
                    val = this.jTValorDet.getText();
                    Determinacion det = (Determinacion) this.jCBDeterminacion.getSelectedItem();
                    Analisisdeterminacion newAD = new Analisisdeterminacion();
                    newAD.setIdAnalisis(anali);
                    newAD.setIdDeterminacion(det);
                    newAD.setValor(val);
                    this.jTValorDet.setText("");
                    controladorDet.create(newAD);
                    JOptionPane.showMessageDialog(null, "Determinacion agregada con éxito", "Información", JOptionPane.INFORMATION_MESSAGE);
                    actualizaTablaDeterminacion();

                } catch (Exception ex) {
                    Logger.getLogger(jDialogCliente.class.getName()).log(Level.SEVERE, null, ex);
                    JOptionPane.showMessageDialog(null, "Error al agregar la determinacion", "Información", JOptionPane.ERROR_MESSAGE);
                }

            }

        } else {
            JOptionPane.showMessageDialog(null, "Debe seleccionar un Analisis", "Validación", JOptionPane.WARNING_MESSAGE);
        }

    }//GEN-LAST:event_jBAgregar1ActionPerformed

    private void jBEditar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBEditar1ActionPerformed

        if (this.jTableDeterminacion.getSelectedRowCount() == 1) {
            seleccionaDeterminacion();
            try {
                controladorDet.destroy(AD.getIdAnalisisDeterminacion());
            } catch (NonexistentEntityException ex) {
                Logger.getLogger(jDialogAnalisis.class.getName()).log(Level.SEVERE, null, ex);
                JOptionPane.showMessageDialog(null, "Error al eliminar la determinacion", "Información", JOptionPane.ERROR_MESSAGE);
            }
            actualizaTablaDeterminacion();

        } else {

            JOptionPane.showMessageDialog(null, "Debe seleccionar una determinacion", "Validación", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_jBEditar1ActionPerformed

    private void jTValorDetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTValorDetActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTValorDetActionPerformed

    private void jTableAnalisisMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableAnalisisMouseClicked
        // TODO add your handling code here:
        actualizaTablaDeterminacion();
    }//GEN-LAST:event_jTableAnalisisMouseClicked

    private void jTableAnalisisKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTableAnalisisKeyReleased
        // TODO add your handling code here:
        actualizaTablaDeterminacion();
    }//GEN-LAST:event_jTableAnalisisKeyReleased

    private void jBVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBVolverActionPerformed
        this.processWindowEvent(new WindowEvent(this, WindowEvent.WINDOW_CLOSING));
    }//GEN-LAST:event_jBVolverActionPerformed

    private void jBImprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBImprimirActionPerformed
        // TODO add your handling code here:
        if (this.jTableAnalisis.getSelectedRowCount() == 1) {
            seleccionaAnalisis();
            try {
                Conexion conn = new Conexion();
                conn.conectar();
                HashMap parameterMap = new HashMap();
                parameterMap.put("pAnalisis", anali.getIdAnalisis());
                java.io.File file = new java.io.File("TestWindow.java");
                String path = file.getAbsolutePath();
                String only_path = path.substring(0, path.lastIndexOf('\\'));
                JasperPrint reporte = JasperFillManager.fillReport(only_path + "/reportAnalisis.jasper", parameterMap, conn.getConn());
                JasperViewer visor = new JasperViewer(reporte, false);
                visor.setVisible(true);
                visor.setDefaultCloseOperation(javax.swing.JDialog.HIDE_ON_CLOSE);
                conn.desconectar();
            } catch (Exception ex) {

                Logger.getLogger(jDialogDescargas.class.getName()).log(Level.SEVERE, null, ex);
            }

        } else {
            JOptionPane.showMessageDialog(null, "Debe seleccionar un Analisis", "Validación", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_jBImprimirActionPerformed
    //Convierte la fila seleccionada en objeto cliente
    @SuppressWarnings("empty-statement")
    private void seleccionaAnalisis() {
        if (this.jTableAnalisis.getSelectedRowCount() == 1) {
            anali = analisisList.get(jTableAnalisis.getSelectedRow());
            this.jTextObs.setText(anali.getObservaciones());
//            DateFormat formatter = new SimpleDateFormat("yyyyMMdd");
//            try{
//            Date date = (Date)formatter.parse(anali.getFecha().toString()); 
//            Calendar cal=Calendar.getInstance();
//            cal.setTime(date);
//            this.dCFecha.setSelectedDate(cal);
//            } catch (Exception ex) {
//                Logger.getLogger(jDialogAnalisis.class.getName()).log(Level.SEVERE, null, ex);
//            }
        }
    }

    private void seleccionaDeterminacion() {
        if (this.jTableDeterminacion.getSelectedRowCount() == 1) {
            AD = analisisdeterminacionList.get(jTableDeterminacion.getSelectedRow());

        }
    }

    //Limpia los textFields
    private void limpiaCampos() {

        this.jTextObs.setText("");

    }

    private Date obtieneFecha() {
        String fechaS = this.dCFecha.getText();
        Date fechaD = null;
        try {
            fechaD = (Date) new SimpleDateFormat("dd/MM/yyyy").parse(fechaS);

        } catch (ParseException ex) {
            Logger.getLogger(jDialogAnalisis.class.getName()).log(Level.SEVERE, null, ex);
        }
        return fechaD;
    }

    //desactiva los textfields y botones de aceptar y cancelar
    private void desactivaCampos() {
        for (Component component : jPanelDatos.getComponents()) {
            component.setEnabled(false);
        }
        this.jTextObs.setEnabled(false);   //enableInputMethods(false);

    }

    //activa los textfields y botones de aceptar y cancelar
    private void activaCampos() {
        for (Component component : jPanelDatos.getComponents()) {
            component.setEnabled(true);
        }
        this.jTextObs.setEnabled(true);

    }

    //desactiva botones de agregar y editar y tabla 
    private void desactivaTabla() {
        for (Component component : jPanelTabla.getComponents()) {
            component.setEnabled(false);
        }
        this.jTableAnalisis.setEnabled(false);

    }
    //activa botones de agregar y editar y tabla 

    private void activaTabla() {
        for (Component component : jPanelTabla.getComponents()) {
            component.setEnabled(true);
        }
        this.jTableAnalisis.setEnabled(true);

    }

    private void actualizaTabla() {
        analisisList.clear();
        analisisList.addAll(analisisQuery.getResultList());
    }

    private void actualizaTablaDeterminacion() {
        analisisdeterminacionList.clear();

        seleccionaAnalisis();
        try {
            if (anali.getIdAnalisis() > 0) {

                analisisdeterminacionQuery = java.beans.Beans.isDesignTime() ? null : SegTAPUEntityManager.createQuery("SELECT a FROM Analisisdeterminacion a WHERE a.idAnalisis = :pAnalisis").setParameter("pAnalisis", anali);
                analisisdeterminacionList.addAll(analisisdeterminacionQuery.getResultList());

            }
        } catch (Exception ex) {

        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.persistence.EntityManager SegTAPUEntityManager;
    private java.util.List<segta.clases.Analisis> analisisList;
    private javax.persistence.Query analisisQuery;
    private java.util.List<segta.clases.Analisisdeterminacion> analisisdeterminacionList;
    private javax.persistence.Query analisisdeterminacionQuery;
    private datechooser.beans.DateChooserCombo dCFecha;
    private java.util.List<segta.clases.Determinacion> determinacionList;
    private javax.persistence.Query determinacionQuery;
    private javax.swing.JButton jBAceptar;
    private javax.swing.JButton jBAgregar;
    private javax.swing.JButton jBAgregar1;
    private javax.swing.JButton jBCancelar;
    private javax.swing.JButton jBEditar;
    private javax.swing.JButton jBEditar1;
    private javax.swing.JButton jBImprimir;
    private javax.swing.JButton jBVolver;
    private javax.swing.JComboBox<String> jCBDeterminacion;
    private javax.swing.JLabel jDialogDescargasFondo;
    private javax.swing.JLabel jLDeterminaciones;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelDatos;
    private javax.swing.JPanel jPanelDatos1;
    private javax.swing.JPanel jPanelTabla;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField jTValorDet;
    private javax.swing.JTable jTableAnalisis;
    private javax.swing.JTable jTableDeterminacion;
    private javax.swing.JTextField jTextCliente;
    private javax.swing.JTextField jTextDescripcion;
    private javax.swing.JTextField jTextLote;
    private javax.swing.JTextArea jTextObs;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
}
