/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package segta.formularios;

import java.awt.Component;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.HashMap;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.persistence.EntityManager;
import javax.persistence.EntityManagerFactory;
import javax.persistence.Persistence;
import javax.persistence.Query;
import javax.swing.JOptionPane;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableCellRenderer;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.view.JasperViewer;
import segta.Conexion;
import segta.clases.Descargas;
import segta.clases.Proveedor;
import segta.controladores.DescargasJpaController;
import segta.controladores.ProveedorJpaController;
import segta.controladores.TamborJpaController;
import static segta.formularios.inicio.de;

/**
 *
 * @author MODERNIZACION3
 */
public class jDialogDescargas extends javax.swing.JDialog {

    /**
     * Creates new form jDialogDescargas
     */
    /**
     * Centra Componente en la pantalla
     */
    public static void centerComponent(Component c) {
        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        Dimension frameSize = c.getSize();

        if (frameSize.height > screenSize.height) {
            frameSize.height = screenSize.height;
        }

        if (frameSize.width > screenSize.width) {
            frameSize.width = screenSize.width;
        }
        c.setLocation((screenSize.width - frameSize.width) / 2,
                (screenSize.height - frameSize.height) / 2);
    }

    EntityManagerFactory emf = Persistence.createEntityManagerFactory("SegTAPU");
    EntityManager em = emf.createEntityManager();
    DescargasJpaController controladorD = new DescargasJpaController(emf);
    TamborJpaController controladorT = new TamborJpaController(emf);
    ProveedorJpaController controladorP = new ProveedorJpaController(emf);

    String fechaO;
    String control;
    Proveedor apicultor = new Proveedor();

    public jDialogDescargas(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        rsscalelabel.RSScaleLabel.setScaleLabel(jLabelDescargasFondo, "/segta/imagenes/fondo dialog.png");
        desactivarDatos();
        DefaultTableCellRenderer tcr = new DefaultTableCellRenderer();
        tcr.setHorizontalAlignment(SwingConstants.CENTER);
        jTable1.getColumnModel().getColumn(0).setCellRenderer(tcr);
        jTable1.getColumnModel().getColumn(2).setCellRenderer(tcr);
        jTable1.getColumnModel().getColumn(3).setCellRenderer(tcr);
        fechaO = dCCfecha.getText();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        SegTAPUEntityManager = java.beans.Beans.isDesignTime() ? null : javax.persistence.Persistence.createEntityManagerFactory("SegTAPU").createEntityManager();
        descargasQuery = java.beans.Beans.isDesignTime() ? null : SegTAPUEntityManager.createQuery("SELECT d FROM Descargas d ORDER BY d.idDescargas DESC");
        descargasList = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : org.jdesktop.observablecollections.ObservableCollections.observableList(descargasQuery.getResultList());
        proveedorQuery = java.beans.Beans.isDesignTime() ? null : SegTAPUEntityManager.createQuery("SELECT p FROM Proveedor p WHERE p.acopiador is not null ORDER BY p.razonSocial");
        proveedorList = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : org.jdesktop.observablecollections.ObservableCollections.observableList(proveedorQuery.getResultList());
        jPanel3 = new javax.swing.JPanel();
        jBVolver = new javax.swing.JButton();
        jPanelTabla = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jBAgregar = new javax.swing.JButton();
        jBEditar = new javax.swing.JButton();
        jBBorrar = new javax.swing.JButton();
        jBCargarTambores = new javax.swing.JButton();
        dCCfechaDesde = new datechooser.beans.DateChooserCombo();
        dCCfechaHasta = new datechooser.beans.DateChooserCombo();
        jTFBuscarCamion = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jBBuscarDescarga = new javax.swing.JButton();
        jBImprimirTambores = new javax.swing.JButton();
        jBBuscarTambor = new javax.swing.JButton();
        jBImprimirRecibo = new javax.swing.JButton();
        jPanelDatos = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTFCamion = new javax.swing.JTextField();
        jTFObservaciones = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        jBAceptar = new javax.swing.JButton();
        jBCancelar = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        dCCfecha = new datechooser.beans.DateChooserCombo();
        jLabel7 = new javax.swing.JLabel();
        jTFObsTambores = new javax.swing.JTextArea();
        jLabelDescargasFondo = new javax.swing.JLabel();

        Proveedor p = new Proveedor();
        p.setRazonSocial("");
        proveedorList.add(0,p);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("DESCARGAS");
        setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jBVolver.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jBVolver.setIcon(new javax.swing.ImageIcon(getClass().getResource("/segta/imagenes/volver icono.png"))); // NOI18N
        jBVolver.setText("VOLVER");
        jBVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBVolverActionPerformed(evt);
            }
        });

        jPanelTabla.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "DESCARGAS", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 18))); // NOI18N

        jTable1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        org.jdesktop.swingbinding.JTableBinding jTableBinding = org.jdesktop.swingbinding.SwingBindings.createJTableBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, descargasList, jTable1);
        org.jdesktop.swingbinding.JTableBinding.ColumnBinding columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${idDescargas}"));
        columnBinding.setColumnName("Descarga");
        columnBinding.setColumnClass(Integer.class);
        columnBinding.setEditable(false);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${fecha}"));
        columnBinding.setColumnName("Fecha");
        columnBinding.setColumnClass(java.util.Date.class);
        columnBinding.setEditable(false);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${camion}"));
        columnBinding.setColumnName("Camion");
        columnBinding.setColumnClass(String.class);
        columnBinding.setEditable(false);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${obsTambores}"));
        columnBinding.setColumnName("Obs. Tambores");
        columnBinding.setColumnClass(String.class);
        columnBinding.setEditable(false);
        bindingGroup.addBinding(jTableBinding);
        jTableBinding.bind();
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setMinWidth(100);
            jTable1.getColumnModel().getColumn(0).setPreferredWidth(100);
            jTable1.getColumnModel().getColumn(0).setMaxWidth(200);
            jTable1.getColumnModel().getColumn(1).setMinWidth(100);
            jTable1.getColumnModel().getColumn(1).setPreferredWidth(100);
            jTable1.getColumnModel().getColumn(1).setMaxWidth(200);
            jTable1.getColumnModel().getColumn(2).setMinWidth(200);
            jTable1.getColumnModel().getColumn(2).setPreferredWidth(200);
            jTable1.getColumnModel().getColumn(2).setMaxWidth(200);
        }

        jBAgregar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jBAgregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/segta/imagenes/add icono.png"))); // NOI18N
        jBAgregar.setText("AGREGAR");
        jBAgregar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jBAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAgregarActionPerformed(evt);
            }
        });

        jBEditar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jBEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/segta/imagenes/editar.png"))); // NOI18N
        jBEditar.setText("EDITAR");
        jBEditar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jBEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBEditarActionPerformed(evt);
            }
        });

        jBBorrar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jBBorrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/segta/imagenes/borrar.png"))); // NOI18N
        jBBorrar.setText("BORRAR");
        jBBorrar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jBBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBBorrarActionPerformed(evt);
            }
        });

        jBCargarTambores.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jBCargarTambores.setIcon(new javax.swing.ImageIcon(getClass().getResource("/segta/imagenes/tambor.png"))); // NOI18N
        jBCargarTambores.setText("TAMBORES");
        jBCargarTambores.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jBCargarTambores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBCargarTamboresActionPerformed(evt);
            }
        });

        dCCfechaDesde.setNothingAllowed(false);
        dCCfechaDesde.setWeekStyle(datechooser.view.WeekDaysStyle.SHORT);
        try {
            dCCfechaDesde.setDefaultPeriods(new datechooser.model.multiple.PeriodSet(new datechooser.model.multiple.Period(new java.util.GregorianCalendar(2020, 0, 1),
                new java.util.GregorianCalendar(2020, 0, 1))));
    } catch (datechooser.model.exeptions.IncompatibleDataExeption e1) {
        e1.printStackTrace();
    }
    dCCfechaDesde.setFieldFont(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 20));
    dCCfechaDesde.setBehavior(datechooser.model.multiple.MultyModelBehavior.SELECT_SINGLE);

    dCCfechaHasta.setNothingAllowed(false);
    dCCfechaHasta.setWeekStyle(datechooser.view.WeekDaysStyle.SHORT);
    dCCfechaHasta.setFieldFont(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 20));
    dCCfechaHasta.setBehavior(datechooser.model.multiple.MultyModelBehavior.SELECT_SINGLE);

    jTFBuscarCamion.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

    jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
    jLabel3.setText("Desde");

    jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
    jLabel4.setText("Hasta");

    jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
    jLabel6.setText("Camion");

    jBBuscarDescarga.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
    jBBuscarDescarga.setIcon(new javax.swing.ImageIcon(getClass().getResource("/segta/imagenes/buscar icono.png"))); // NOI18N
    jBBuscarDescarga.setText("Buscar");
    jBBuscarDescarga.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jBBuscarDescargaActionPerformed(evt);
        }
    });

    jBImprimirTambores.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
    jBImprimirTambores.setIcon(new javax.swing.ImageIcon(getClass().getResource("/segta/imagenes/clasificar icono.png"))); // NOI18N
    jBImprimirTambores.setText("LISTADO");
    jBImprimirTambores.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
    jBImprimirTambores.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jBImprimirTamboresActionPerformed(evt);
        }
    });

    jBBuscarTambor.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
    jBBuscarTambor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/segta/imagenes/buscar icono.png"))); // NOI18N
    jBBuscarTambor.setText("BUSCAR");
    jBBuscarTambor.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
    jBBuscarTambor.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jBBuscarTamborActionPerformed(evt);
        }
    });

    jBImprimirRecibo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
    jBImprimirRecibo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/segta/imagenes/report2.png"))); // NOI18N
    jBImprimirRecibo.setText("RECIBO");
    jBImprimirRecibo.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
    jBImprimirRecibo.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jBImprimirReciboActionPerformed(evt);
        }
    });

    javax.swing.GroupLayout jPanelTablaLayout = new javax.swing.GroupLayout(jPanelTabla);
    jPanelTabla.setLayout(jPanelTablaLayout);
    jPanelTablaLayout.setHorizontalGroup(
        jPanelTablaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanelTablaLayout.createSequentialGroup()
            .addContainerGap()
            .addGroup(jPanelTablaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jScrollPane1)
                .addGroup(jPanelTablaLayout.createSequentialGroup()
                    .addGroup(jPanelTablaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(dCCfechaDesde, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel3))
                    .addGap(18, 18, 18)
                    .addGroup(jPanelTablaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(dCCfechaHasta, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel4))
                    .addGap(50, 50, 50)
                    .addGroup(jPanelTablaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanelTablaLayout.createSequentialGroup()
                            .addComponent(jLabel6)
                            .addGap(0, 0, Short.MAX_VALUE))
                        .addGroup(jPanelTablaLayout.createSequentialGroup()
                            .addComponent(jTFBuscarCamion, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(jBBuscarDescarga, javax.swing.GroupLayout.DEFAULT_SIZE, 159, Short.MAX_VALUE))
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelTablaLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addGroup(jPanelTablaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jBAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanelTablaLayout.createSequentialGroup()
                            .addComponent(jBCargarTambores, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jBBuscarTambor, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(jPanelTablaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jBEditar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jBImprimirRecibo, javax.swing.GroupLayout.DEFAULT_SIZE, 163, Short.MAX_VALUE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(jPanelTablaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jBImprimirTambores, javax.swing.GroupLayout.DEFAULT_SIZE, 164, Short.MAX_VALUE)
                        .addGroup(jPanelTablaLayout.createSequentialGroup()
                            .addComponent(jBBorrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGap(6, 6, 6)))))
            .addContainerGap())
    );
    jPanelTablaLayout.setVerticalGroup(
        jPanelTablaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanelTablaLayout.createSequentialGroup()
            .addGroup(jPanelTablaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelTablaLayout.createSequentialGroup()
                    .addGap(12, 12, 12)
                    .addGroup(jPanelTablaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(jLabel4)))
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelTablaLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabel6)))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(jPanelTablaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                .addComponent(dCCfechaDesde, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(dCCfechaHasta, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jTFBuscarCamion, javax.swing.GroupLayout.Alignment.TRAILING)
                .addComponent(jBBuscarDescarga, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGap(28, 28, 28)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addGroup(jPanelTablaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jBAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jBEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jBBorrar, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addGroup(jPanelTablaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jBCargarTambores, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jBImprimirTambores, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jBBuscarTambor, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jBImprimirRecibo, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );

    jPanelDatos.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "DATOS DE LA DESCARGA", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 18))); // NOI18N

    jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
    jLabel1.setText("CAMIÓN");

    jTFCamion.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

    org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, jTable1, org.jdesktop.beansbinding.ELProperty.create("${selectedElement.camion}"), jTFCamion, org.jdesktop.beansbinding.BeanProperty.create("text"));
    bindingGroup.addBinding(binding);

    jTFObservaciones.setColumns(20);
    jTFObservaciones.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
    jTFObservaciones.setRows(5);

    binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, jTable1, org.jdesktop.beansbinding.ELProperty.create("${selectedElement.observaciones}"), jTFObservaciones, org.jdesktop.beansbinding.BeanProperty.create("text"));
    bindingGroup.addBinding(binding);

    jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
    jLabel2.setText("OBSERVACIONES");

    jBAceptar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
    jBAceptar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/segta/imagenes/aceptar.png"))); // NOI18N
    jBAceptar.setText("ACEPTAR");
    jBAceptar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
    jBAceptar.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jBAceptarActionPerformed(evt);
        }
    });

    jBCancelar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
    jBCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/segta/imagenes/cancerlar.png"))); // NOI18N
    jBCancelar.setText("CANCELAR");
    jBCancelar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
    jBCancelar.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jBCancelarActionPerformed(evt);
        }
    });

    jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
    jLabel5.setText("FECHA");

    dCCfecha.setWeekStyle(datechooser.view.WeekDaysStyle.SHORT);
    dCCfecha.setFieldFont(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 18));

    jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
    jLabel7.setText("OBSERVACIONES TAMBORES");

    jTFObsTambores.setEditable(false);
    jTFObsTambores.setColumns(10);
    jTFObsTambores.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
    jTFObsTambores.setLineWrap(true);
    jTFObsTambores.setRows(20);

    javax.swing.GroupLayout jPanelDatosLayout = new javax.swing.GroupLayout(jPanelDatos);
    jPanelDatos.setLayout(jPanelDatosLayout);
    jPanelDatosLayout.setHorizontalGroup(
        jPanelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanelDatosLayout.createSequentialGroup()
            .addGroup(jPanelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelDatosLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jBAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jBCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanelDatosLayout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(jPanelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanelDatosLayout.createSequentialGroup()
                            .addComponent(jLabel2)
                            .addGap(0, 0, Short.MAX_VALUE))
                        .addComponent(jTFObsTambores)
                        .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTFObservaciones)))
                .addGroup(jPanelDatosLayout.createSequentialGroup()
                    .addGroup(jPanelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanelDatosLayout.createSequentialGroup()
                            .addGap(33, 33, 33)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelDatosLayout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jLabel5)))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(jPanelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(dCCfecha, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTFCamion, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addContainerGap())
    );
    jPanelDatosLayout.setVerticalGroup(
        jPanelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanelDatosLayout.createSequentialGroup()
            .addGap(34, 34, 34)
            .addGroup(jPanelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 51, Short.MAX_VALUE)
                .addComponent(dCCfecha, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
            .addGroup(jPanelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jTFCamion, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jTFObservaciones, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(39, 39, 39)
            .addComponent(jLabel7)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addComponent(jTFObsTambores, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(jPanelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jBCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jBAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)))
    );

    javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
    jPanel3.setLayout(jPanel3Layout);
    jPanel3Layout.setHorizontalGroup(
        jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
        .addGroup(jPanel3Layout.createSequentialGroup()
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanelDatos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(18, 18, 18)
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                .addComponent(jPanelTabla, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jBVolver, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addContainerGap(18, Short.MAX_VALUE))
    );
    jPanel3Layout.setVerticalGroup(
        jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel3Layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanelDatos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addComponent(jPanelTabla, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(18, 18, 18)
                    .addComponent(jBVolver, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addContainerGap(14, Short.MAX_VALUE))
    );

    getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 20, 1160, 670));

    jLabelDescargasFondo.setDisplayedMnemonic('D');
    jLabelDescargasFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/segta/imagenes/fondo dialog.png"))); // NOI18N
    getContentPane().add(jLabelDescargasFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1370, 740));

    bindingGroup.bind();

    pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBAgregarActionPerformed

        activarDatos();
        desactivarTabla();
        jTFCamion.setText("");
        jTFObservaciones.setText("");
        jTFObsTambores.selectAll();
        jTFObsTambores.replaceSelection("");
        control = "agregar";


    }//GEN-LAST:event_jBAgregarActionPerformed
    private void jBEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBEditarActionPerformed

        if (this.jTable1.getSelectedRowCount() == 1) {

            de = descargasList.get(jTable1.getSelectedRow());
            try {
                Calendar cal = Calendar.getInstance();
                cal.setTime(de.getFecha());
                this.dCCfecha.setSelectedDate(cal);
            } catch (Exception ex) {
                Logger.getLogger(jDialogAnalisis.class.getName()).log(Level.SEVERE, null, ex);
            }
            activarDatos();
            desactivarTabla();
            control = "editar";
        } else {
            JOptionPane.showMessageDialog(null, "Debe seleccionar una descarga", "Validación", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_jBEditarActionPerformed
    private void actualizarTabla() {

        jTFCamion.setText("");
        jTFObservaciones.setText("");
        jTFObsTambores.selectAll();
        jTFObsTambores.replaceSelection("");
        jTFCamion.requestFocus();
        descargasList.clear();
        descargasQuery = java.beans.Beans.isDesignTime() ? null : SegTAPUEntityManager.createQuery("SELECT d FROM Descargas d ORDER BY d.idDescargas DESC");
        descargasList.addAll(descargasQuery.getResultList());
//        jComboBoxApicultor.setSelectedIndex(0);
    }

    private void activarDatos() {
        for (Component component : jPanelDatos.getComponents()) {
            component.setEnabled(true);
        }
    }

    private void desactivarDatos() {
        for (Component component : jPanelDatos.getComponents()) {
            component.setEnabled(false);
        }
    }

    private void activarTabla() {
        for (Component component : jPanelTabla.getComponents()) {
            component.setEnabled(true);
        }
        this.jTable1.setEnabled(true);
    }

    private void desactivarTabla() {
        for (Component component : jPanelTabla.getComponents()) {
            component.setEnabled(false);
        }
        this.jTable1.setEnabled(false);
    }
    private void jBCargarTamboresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBCargarTamboresActionPerformed

        if (this.jTable1.getSelectedRowCount() == 1) {
            de = descargasList.get(jTable1.getSelectedRow());
            new jDialogTambores(this, true).setVisible(true);
        } else {
            JOptionPane.showMessageDialog(null, "Debe seleccionar una descarga", "Validación", JOptionPane.WARNING_MESSAGE);
        }


    }//GEN-LAST:event_jBCargarTamboresActionPerformed

    private void jBAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBAceptarActionPerformed

        Descargas nuevaDescarga = new Descargas();
//        apicultor = (Proveedor) this.jComboBoxApicultor.getSelectedItem();

        if (jTFCamion.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Completar datos de camion");
            jTFCamion.requestFocus();
        } else {
            if (jTFObservaciones.getText() == "") {
                jTFObservaciones.setText(" ");
            }

            String fechaS = dCCfecha.getText();

            try {
                Date fechaD = (Date) new SimpleDateFormat("dd/MM/yy").parse(fechaS);
                nuevaDescarga.setFecha(fechaD);
            } catch (ParseException ex) {
                JOptionPane.showMessageDialog(null, "Error al registrar la fecha", "Información", JOptionPane.ERROR_MESSAGE);
                Logger.getLogger(jDialogDescargas.class.getName()).log(Level.SEVERE, null, ex);
            }
            if (control == "agregar") {
                nuevaDescarga.setCamion(jTFCamion.getText());
                nuevaDescarga.setObservaciones(jTFObservaciones.getText());
//                if (apicultor.getRazonSocial() != "") {
//                    nuevaDescarga.setIdProveedor(apicultor);
//                }
                try {
                    controladorD.create(nuevaDescarga);
                    JOptionPane.showMessageDialog(null, "Descarga Agregada");
                } catch (Exception ex) {
                    JOptionPane.showMessageDialog(null, "Error al agregr la descarga", "Información", JOptionPane.ERROR_MESSAGE);
                    Logger.getLogger(jDialogDescargas.class.getName()).log(Level.SEVERE, null, ex);
                }

            } else if (control == "editar") {

                de.setCamion(jTFCamion.getText());
                de.setObservaciones(jTFObservaciones.getText());
//                de.setIdProveedor(apicultor);
                try {
                    Date fechaD = (Date) new SimpleDateFormat("dd/MM/yy").parse(fechaS);
                    de.setFecha(fechaD);
                } catch (ParseException ex) {
                    JOptionPane.showMessageDialog(null, "Error al registrar la fecha", "Información", JOptionPane.ERROR_MESSAGE);
                    Logger.getLogger(jDialogDescargas.class.getName()).log(Level.SEVERE, null, ex);
                }

                try {
                    controladorD.edit(de);
                    JOptionPane.showMessageDialog(null, "Descarga actualizada");
                    actualizarTabla();
                } catch (Exception ex) {
                    JOptionPane.showMessageDialog(null, "Error al editar la descarga", "Información", JOptionPane.ERROR_MESSAGE);
                    Logger.getLogger(jDialogDescargas.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
            desactivarDatos();
            activarTabla();
            actualizarTabla();
        }
    }//GEN-LAST:event_jBAceptarActionPerformed

    private void jBCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBCancelarActionPerformed
        desactivarDatos();
        activarTabla();
        actualizarTabla();
    }//GEN-LAST:event_jBCancelarActionPerformed

    private void jBBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBBorrarActionPerformed
        if (this.jTable1.getSelectedRowCount() == 1) {
            Descargas desc = descargasList.get(jTable1.getSelectedRow());
            if (desc.getTamborCollection().isEmpty()) {
                if (JOptionPane.showConfirmDialog(null, "Desea borrar la descarga?", "Atención", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
                    try {
                        controladorD.destroy(desc.getIdDescargas());
                        JOptionPane.showMessageDialog(null, "Descarga borrada");
                        actualizarTabla();
                    } catch (Exception ex) {
                        JOptionPane.showMessageDialog(null, "Error al borrar la descarga", "Información", JOptionPane.ERROR_MESSAGE);
                        Logger.getLogger(jDialogDescargas.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }

            } else {
                JOptionPane.showMessageDialog(null, "No se puede borrar la descarga, tiene tambores asociados", "Validación", JOptionPane.WARNING_MESSAGE);
            }

        } else {
            JOptionPane.showMessageDialog(null, "Debe seleccionar una descarga", "Validación", JOptionPane.WARNING_MESSAGE);
        }

    }//GEN-LAST:event_jBBorrarActionPerformed

    private void jBVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBVolverActionPerformed
        this.processWindowEvent(new WindowEvent(this, WindowEvent.WINDOW_CLOSING));        // TODO add your handling code here:
    }//GEN-LAST:event_jBVolverActionPerformed

    private void jBBuscarDescargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBBuscarDescargaActionPerformed

        String fechaDesde = dCCfechaDesde.getText();
        String fechaHasta = dCCfechaHasta.getText();
        String paramCamion = '%' + this.jTFBuscarCamion.getText() + '%';
        Date fechaD = null;
        Date fechaH = null;
        try {
            fechaD = (Date) new SimpleDateFormat("dd/MM/yy").parse(fechaDesde);
        } catch (ParseException ex) {
            Logger.getLogger(jDialogDescargas.class.getName()).log(Level.SEVERE, null, ex);
        }

        try {
            fechaH = (Date) new SimpleDateFormat("dd/MM/yy").parse(fechaHasta);
        } catch (ParseException ex) {
            Logger.getLogger(jDialogDescargas.class.getName()).log(Level.SEVERE, null, ex);
        }

        Query queryDesc = SegTAPUEntityManager.createQuery("SELECT d FROM Descargas d WHERE d.camion like :camion AND  d.fecha BETWEEN :fechaDesde AND :fechaHasta ORDER BY d.fecha DESC");
        queryDesc.setParameter("fechaDesde", fechaD);
        queryDesc.setParameter("fechaHasta", fechaH);
        queryDesc.setParameter("camion", paramCamion);

        descargasQuery = java.beans.Beans.isDesignTime() ? null : queryDesc;
        descargasList.clear();
        descargasList.addAll(descargasQuery.getResultList());
    }//GEN-LAST:event_jBBuscarDescargaActionPerformed

    private void jBBuscarTamborActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBBuscarTamborActionPerformed
        jDialogBuscarTambor dialog = new jDialogBuscarTambor(new javax.swing.JDialog(), true);
        dialog.setVisible(true);
    }//GEN-LAST:event_jBBuscarTamborActionPerformed

    private void jBImprimirReciboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBImprimirReciboActionPerformed
        if (this.jTable1.getSelectedRowCount() == 1) {
            try {
                Conexion conn = new Conexion();
                Descargas desc = descargasList.get(jTable1.getSelectedRow());
                conn.conectar();
                HashMap parameterMap = new HashMap();
                parameterMap.put("desc", desc.getIdDescargas());
                java.io.File file = new java.io.File("TestWindow.java");
                String path = file.getAbsolutePath();
                String only_path = path.substring(0, path.lastIndexOf('\\'));
                JasperPrint reporte = JasperFillManager.fillReport(only_path + "/reportTamborRecibo.jasper", parameterMap, conn.getConn());
                JasperViewer visor = new JasperViewer(reporte, false);
                visor.setVisible(true);
                visor.setDefaultCloseOperation(javax.swing.JDialog.HIDE_ON_CLOSE);
                conn.desconectar();
            } catch (Exception ex) {

                Logger.getLogger(jDialogDescargas.class.getName()).log(Level.SEVERE, null, ex);
            }

        } else {
            JOptionPane.showMessageDialog(null, "Debe seleccionar una descarga", "Validación", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_jBImprimirReciboActionPerformed

    private void jBImprimirTamboresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBImprimirTamboresActionPerformed
        if (this.jTable1.getSelectedRowCount() == 1) {
            try {
                Conexion conn = new Conexion();
                Descargas desc = descargasList.get(jTable1.getSelectedRow());
                conn.conectar();
                HashMap parameterMap = new HashMap();
                parameterMap.put("desc", desc.getIdDescargas());
                java.io.File file = new java.io.File("TestWindow.java");
                String path = file.getAbsolutePath();
                String only_path = path.substring(0, path.lastIndexOf('\\'));
                JasperPrint reporte = JasperFillManager.fillReport(only_path + "/reportTamborDescarga.jasper", parameterMap, conn.getConn());
                JasperViewer visor = new JasperViewer(reporte, false);
                visor.setVisible(true);
                visor.setDefaultCloseOperation(javax.swing.JDialog.HIDE_ON_CLOSE);
                conn.desconectar();
            } catch (Exception ex) {

                Logger.getLogger(jDialogDescargas.class.getName()).log(Level.SEVERE, null, ex);
            }

        } else {
            JOptionPane.showMessageDialog(null, "Debe seleccionar una descarga", "Validación", JOptionPane.WARNING_MESSAGE);
        }        // TODO add your handling code here:
    }//GEN-LAST:event_jBImprimirTamboresActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        de = descargasList.get(jTable1.getSelectedRow());
        this.jTFObsTambores.setText(de.getObsTambores());
//        this.jComboBoxApicultor.setSelectedItem(de.getIdProveedor());
    }//GEN-LAST:event_jTable1MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.persistence.EntityManager SegTAPUEntityManager;
    private datechooser.beans.DateChooserCombo dCCfecha;
    private datechooser.beans.DateChooserCombo dCCfechaDesde;
    private datechooser.beans.DateChooserCombo dCCfechaHasta;
    private java.util.List<segta.clases.Descargas> descargasList;
    private javax.persistence.Query descargasQuery;
    private javax.swing.JButton jBAceptar;
    private javax.swing.JButton jBAgregar;
    private javax.swing.JButton jBBorrar;
    private javax.swing.JButton jBBuscarDescarga;
    private javax.swing.JButton jBBuscarTambor;
    private javax.swing.JButton jBCancelar;
    private javax.swing.JButton jBCargarTambores;
    private javax.swing.JButton jBEditar;
    private javax.swing.JButton jBImprimirRecibo;
    private javax.swing.JButton jBImprimirTambores;
    private javax.swing.JButton jBVolver;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabelDescargasFondo;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanelDatos;
    private javax.swing.JPanel jPanelTabla;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTFBuscarCamion;
    private javax.swing.JTextField jTFCamion;
    private javax.swing.JTextArea jTFObsTambores;
    private javax.swing.JTextArea jTFObservaciones;
    private javax.swing.JTable jTable1;
    private java.util.List<segta.clases.Proveedor> proveedorList;
    private javax.persistence.Query proveedorQuery;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
}
